name: Build and Deploy to Amazon ECR

on:
  workflow_dispatch:
    inputs:
      dockerTag:
        description: 'Docker image tag instead of branch name'
        required: false
        type: string
  push:
    branches:
      - master
    tags:
      - '*.*.*'

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: php-fpm
  DOCKER_BUILDKIT: 1
  PHP_VERSION: 8.1

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      -
        name: Generate tag name
        id: tag-generate
        env:
          INPUT_TAG: ${{ github.event.inputs.dockerTag }}
        run: |
          TAG="${INPUT_TAG:-$GITHUB_REF_NAME}"
          TAG="${TAG/\//-}"
          echo "::set-output name=tag::${TAG,,}"
      -
        name: Builder build and push
        uses: docker/build-push-action@v2
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          context: .
# arm64 builds were taking ~45 minutes to run on GitHub cloud. Only building amd64 for now.
#          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref_name == 'master' || startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch' }}
          tags: ${{ env.ECR_REGISTRY}}/${{ env.ECR_REPOSITORY }}:${{ env.PHP_VERSION }}-builder-${{ steps.tag-generate.outputs.tag }}
          target: builder
      -
        name: Nginx build and push
        uses: docker/build-push-action@v2
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          context: .
# arm64 builds were taking ~45 minutes to run on GitHub cloud. Only building amd64 for now.
#          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref_name == 'master' || startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch' }}
          tags: ${{ env.ECR_REGISTRY}}/${{ env.ECR_REPOSITORY }}:${{ env.PHP_VERSION }}-nginx-${{ steps.tag-generate.outputs.tag }}
          target: hosting
