name: Build

on:
  pull_request:
    branches:
      - master

env:
  DOCKER_BUILDKIT: 1

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build Nginx
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          target: hosting
      -
        name: Build Builder
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          target: builder
